Always check for erros

diff --git a/databox-start b/databox-start
--- a/databox-start
+++ b/databox-start
@@ -19,7 +19,7 @@ die() {
 assert() {
   if [ "$1" != "$2" ] 
   then
-    die 1 $3
+    die 1 "ERROR: ${3}"
   fi
 }
 
@@ -66,11 +66,7 @@ fi
 ## test if Databox is already running
 err "testing if Databox is already running ..."
 docker node ls >/dev/null 2>&1
-if [[ $? -eq 0 ]]; then
-  die 0 "Databox is already running!"
-else
-  err "starting Databox ..."
-fi
+assert $? 1 "Databox is already running!"
 
 ## extract a host interface IP address
 err "extracting host interface IP address ..."
@@ -146,27 +142,25 @@ then
   # build all images locally in dev mode
   err "Building Databox localy in dev mode"
   ./databox-fetch-components
-  #docker-compose build
   source ./databox-build-core
-  if [ "$?" != "0" ] 
-  then
-    die 1 "Problem building core images"
-  fi 
+  assert $? 0 "Problem building core images"
   if [ -z "$DATABOX_TESTING" ]
   then
     # dont build these optional components when testing
     docker-compose -f ./docker-compose-dev-local-images.yaml build
+    assert $? 0 "Problem building optional images"
   fi
 fi
 
 err "starting Databox"
-#docker-compose -f ./docker-databox-appstore.yaml up -d
+docker-compose -f ./docker-databox-appstore.yaml up -d
 docker stack deploy -c docker-compose.yaml databox
+assert $? 0 "Problem with docker stack deploy"
 
 DARGS="-e DATABOX_DEV=$DEV"
 err "seeding manifests"
 _exec node ./src/seedManifests.js
-assert $? 0 "ERROR: Failed to seed manifests app-store not found"
+assert $? 0 "Failed to seed manifests app-store not found"
 
 err "Databox started! Visit http://127.0.0.1:8989"
 if [ -z "$DATABOX_TESTING" ]
