Improve integration tests (#251)
* Allow selection of dev|latest|release in the test scripts

* Add a test for Docker DNS resolution

* Adds tests for restart and reinstall of app driver pair

* Add encrypted GitHub key to travis.yml

* move to databoxsystems/githubreleasetool image

* Get Travis-CI to build the documentation

* Fix GitHubReleaseTool Config path

* Add a config file for docs generation and commit docs back to git hub on commits to the master branch

* Increase test timeouts
 
* Speed up the unit tests unless databox-components has been modified

* Added debug output on test fail to help pinpoint failures

* add timestamps to debug output on failure

* Update tests to select registry

* Adds test for restarting databox will app driver pair installed

diff --git a/databox-start b/databox-start
--- a/databox-start
+++ b/databox-start
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-#makesure we are in the right dir
+#make sure we are in the right dir
 MY_PATH="`dirname \"$0\"`"              # relative
 MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
 cd "${MY_PATH}"
@@ -24,8 +24,40 @@ if ! [ -x "$(command -v docker)" ]; then
 fi
 
 if ! [ -x "$(command -v docker-compose)" ]; then
-  die 2 "docker-compose is not installed;"`
+  die 1 "docker-compose is not installed;"`
        `"see https://docs.docker.com/compose/install/#install-compose"
+fi
+
+
+## base images: what are we running on?
+ARCH=$(uname -m)
+case "$ARCH" in
+  armv7l )
+    NODE_IMAGE="hypriot/rpi-node:slim"
+    DEV=1 #ARM is only supported in dev mode with locally built images (for now)
+    export DATABOX_ARCH="-"${ARCH}
+    export DATABOX_DEV="1"
+    ;;
+
+  aarch64 )
+    NODE_IMAGE="forumi0721alpineaarch64/alpine-aarch64-nodejs"
+    DEV=1 #ARM is only supported in dev mode with locally built images (for now)
+    export DATABOX_ARCH="-"${ARCH}
+    export DATABOX_DEV="1"
+    ;;
+
+  * )
+    ARCH=""
+    NODE_IMAGE="node:alpine"
+    export DATABOX_ARCH=""
+    ;;
+esac
+
+#test docker dns configuration
+docker run $NODE_IMAGE nslookup google.com >/dev/null 2>&1
+if [[ "$?" == "1" ]]
+then
+  die 1 "[ERROR] DNS test failed: Your docker DNS resolution seems to be broken. Help can be found here https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/"
 fi
 
 ## parse command line args
@@ -91,6 +123,7 @@ if [[ "${#ips[@]}" -gt "1" ]]; then
 fi
 err "host interface IP address = ${HOST_IP}"
 
+
 ## Get the external IP of the databox used for NATed set-ups over HTTPS
 cd dockerfiles/curl
 docker build -t databoxsystems/curl . >/dev/null
@@ -105,30 +138,6 @@ then
   die 1 'Error getting external IP address. Do you have network connectivity?'
 fi
 err "External interface IP address = ${EXT_IP}"
-
-## base images: what are we running on?
-ARCH=$(uname -m)
-case "$ARCH" in
-  armv7l )
-    NODE_IMAGE="hypriot/rpi-node:slim"
-    DEV=1 #ARM is only supported in dev mode with localy built images (for now)
-    export DATABOX_ARCH="-"${ARCH}
-    export DATABOX_DEV="1"
-    ;;
-
-  aarch64 )
-    NODE_IMAGE="forumi0721alpineaarch64/alpine-aarch64-nodejs"
-    DEV=1 #ARM is only supported in dev mode with localy built images (for now)
-    export DATABOX_ARCH="-"${ARCH}
-    export DATABOX_DEV="1"
-    ;;
-
-  * )
-    ARCH=""
-    NODE_IMAGE="node:alpine"
-    export DATABOX_ARCH=""
-    ;;
-esac
 
 DOCKER_REPO=""
 DATABOX_VERSION=$(<./Version)
@@ -187,7 +196,7 @@ _exec node ./src/createCerts.js ${HOST_IP} ${EXT_IP} ${ips[@]}
 if [ "$DEV" == "1" ]
 then
   # build all images locally in dev mode
-  err "Building Databox localy in dev mode"
+  err "Building Databox locally in dev mode"
   ./databox-fetch-components
   source ./databox-build-core
   assert_or_die $? 0 "Problem building core images"
diff --git a/databox-test b/databox-test
--- a/databox-test
+++ b/databox-test
@@ -1,34 +1,38 @@
 #!/bin/bash
 
-function fail {
-    echo -e "[$( red FAILED )] ${1} \nERROR: ${2}"
-    #output debug information
-    echo "docker version:"
-    docker version
-    echo "docker ps \n"
-    docker ps
-    echo "docker image ls \n"
-    docker image ls
-    echo "docker service ls \n"
-    docker service ls
-    echo "service logs databox_container-manager \n"
-    docker service logs databox_container-manager
-    echo "\n"
-    exit 1
+function install_osmon_app_and_driver {
+  #function to install app driver pair
+
+  #can we install the OS monitor driver
+  PAYLOAD="{\"storeUrl\":\"\",\"registry\":\"${DATABOX_SLA_REG}\""
+  REST=', "manifest-version": 1,"name": "driver-os-monitor","version": "0.3.0","description": "A Databox driver to monitor the local os","author": "Anthony Brown <Anthony.Brown@nottingham.ac.uk> ()","license": "MIT","databox-type":"driver","tags": ["monitor","os"],"homepage": "https://github.com/me-box/driver-os-monitor","repository": {"type": "git","url": "git+https://github.com/me-box/driver-os-monitor.git"},"resource-requirements": {    "store":"core-store"}}'
+  PAYLOAD="${PAYLOAD}${REST}"
+  RES=$(curl -s  --insecure --cookie ./databox-jar -H "Content-Type: application/json" -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/install')
+  EXPECTED='{"status":200,"msg":"Success"}'
+  test_assert "$RES" "$EXPECTED" "Can we install the driver-os-monitor?"
+
+  #can we install the OS monitor app
+  PAYLOAD="{\"storeUrl\":\"\",\"registry\":\"${DATABOX_SLA_REG}\""
+  REST=',"manifest-version":1,"name":"app-os-monitor","databox-type":"app","version":"0.3.0","description":"An app in golang to plot the output of the os monitor driver.","author":"Tosh Brown <Anthony.Brown@nottingham.ac.uk>","license":"MIT","tags":["template","app","nodejs"],"homepage":"https://github.com/me-box/app-os-monitor","repository":{"type":"git","url":"git https://github.com/me-box/app-os-monitor"},"packages":[{"name":"OS monitor Plotter","purpose":"To visualize your databox load and free memory","install":"required","risks":"None.","benefits":"You can see the data!","datastores":["loadavg1","loadavg5","loadavg15","freemem","loadavg1Structured","freememStructured"],"enabled":true}],"allowed-combinations":[],"datasources":[{"type":"loadavg1","required":true,"name":"loadavg1","clientid":"loadavg1","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average 1 minute"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg1"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg1"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/loadavg1"}},{"type":"loadavg5","required":true,"name":"loadavg5","clientid":"loadavg5","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average over 5 minutes"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg5"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg5"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/loadavg5"}},{"type":"loadavg15","required":true,"name":"loadavg15","clientid":"loadavg15","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average over 15 minutes"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg15"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg15"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/loadavg15"}},{"type":"freemem","required":true,"name":"freemem","clientid":"freemem","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox free memory in bytes"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"freemem"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"freemem"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"bytes"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/freemem"}},{"type":"loadavg1Structured","required":true,"name":"loadavg1Structured","clientid":"loadavg1Structured","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average 1 minute structured"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg1Structured"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg1Structured"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/loadavg1Structured"}},{"type":"freememStructured","required":true,"name":"freememStructured","clientid":"freememStructured","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox free memory in bytes structured"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"freememStructured"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"freememStructured"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"bytes"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/freememStructured"}}],"export-whitelist":[{"url":"https://export.amar.io/","description":"Exports the data to amar.io"}],"resource-requirements":{},"displayName":"os monitor"}'
+  PAYLOAD="${PAYLOAD}${REST}"
+  RES=$(curl -s  --insecure --cookie ./databox-jar -H 'Content-Type: application/json' -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/install')
+  EXPECTED='{"status":200,"msg":"Success"}'
+  test_assert "$RES" "$EXPECTED" "Can we install the app-os-monitor?"
 }
 
-function success {
-    echo -e "[$( green OK )] $1"
+function test_app_os_monitor {
+  #Function test if app-os-monitor is running and can get data from the store
+
+  #is the OS monitor app up
+  STATUS=$(curl -sL --cookie ./databox-jar -H "authorization:Token ${UI_AUTH_TOKEN}" --insecure -w "%{http_code}\\n" "https://127.0.0.1/app-os-monitor/ui" -o /dev/null)
+  test_assert "$STATUS" 200 "Is the app-os-monitor/ui available?"
+
+  #is the OS monitor app able to get data
+  RES=$(curl -s  --insecure --cookie ./databox-jar -H 'Content-Type: application/json' -H "authorization:Token ${UI_AUTH_TOKEN}" -L 'https://127.0.0.1/app-os-monitor/ui/stats')
+  EXPECTED='"mem":{"min":{"result":'
+  test_assert_contains "$RES" "$EXPECTED" "Can we get data from app-os-monitor?"
 }
 
-function test_assert {
-  if [ "$1" != "$2" ]
-  then
-    fail "$3" "$1"
-  else
-    success "$3"
-  fi
-}
 
 function jsonValue() {
 KEY=$1
@@ -36,18 +40,102 @@ num=$2
 awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
 }
 
-
-rm ./slaStore/sladatastore.db
+# make sure we don't load anything from here
+rm -f ./slaStore/sladatastore.db >/dev/null 2>&1
 
 #Start databox
 export DATABOX_TESTING=1
-source ./databox-start dev
+
+
+case "$1" in
+  travis )
+    echo "travis build checking build type needed"
+    git remote rm origin
+    git remote add origin https://github.com/me-box/databox.git
+    git pull origin master
+    if [[ "$(git diff HEAD origin/master --name-only)" == *"databox-components"* ]]
+    then
+      echo "databox-components has been modified building from source"
+      source ./databox-start dev
+      DATABOX_CMD="./databox-start dev"
+      export DATABOX_SLA_REG="localhost"
+    else
+      echo "databox-components has not been modified using :latest images from databoxsystems on docker hub"
+      source ./databox-start latest
+      export DATABOX_SLA_REG="databoxsystems"
+      DATABOX_CMD="./databox-start latest"
+    fi
+  ;;
+  dev )
+    echo "Testing databox in dev mode building all components from source code"
+    source ./databox-start dev
+    export DATABOX_SLA_REG="localhost"
+    DATABOX_CMD="./databox-start dev"
+    ;;
+  latest )
+    echo "Testing databox in latest using :latest images from databoxsystems on docker hub"
+    source ./databox-start latest
+    export DATABOX_SLA_REG="databoxsystems"
+    DATABOX_CMD="./databox-start latest"
+    ;;
+   release )
+    echo "Testing databox release using images from databoxsystems on docker hub"
+    source ./databox-start
+    export DATABOX_SLA_REG="databoxsystems"
+    DATABOX_CMD="./databox-start"
+    ;;
+  *)
+    echo $'\nRun Databox integration tests:\n'
+    echo $'Usage: databox-test {dev|latest|release}\n'
+    echo $'dev - Tests databox in dev mode building all components from source code'
+    echo $'latest - Tests databox using :latest images from databoxsystems on docker hub (built from master branches on Github)'
+    echo $'release - Tests databox release using images from databoxsystems on docker hub (built from tagged branches on Github) \n\n'
+    exit 1
+esac
+
+#
+# override fail function to provide better debug output mist be after source ./databox-start
+#
+function fail {
+    echo -e "[$( red FAILED )] ${1} \nERROR: ${2}"
+    #output debug information
+    echo "docker version:"
+    docker version
+    echo "docker ps \n"
+    docker ps
+    #echo "docker image ls \n"
+    #docker image ls
+    echo "docker service ls \n"
+    docker service ls
+    echo "service logs --timestamps databox_container-manager \n"
+    docker service logs databox_container-manager
+    echo "\n"
+    echo "service logs --timestamps app-os-monitor \n"
+    docker service logs app-os-monitor
+    echo "\n"
+    echo "service logs --timestamps driver-os-monitor  \n"
+    docker service logs driver-os-monitor
+    echo "\n"
+    echo "logs databox-network  \n"
+    docker logs databox_databox-network_1
+    exit 1
+}
+
+function test_assert_contains {
+  if [[ "$1" != *"$2"* ]]
+  then
+    fail "$3" "$1"
+  else
+    success "$3"
+  fi
+}
+
 
 UI_AUTH_TOKEN=$(cat ./certs/container-mananager-auth.json | jsonValue "token" 1)
 
 echo "Sleeping...."
 docker ps
-sleep 60
+sleep 15
 
 
 #setup the auth cookie
@@ -68,21 +156,65 @@ EXPECTED='{"catalogue-metadata":[{"rel":"urn:X-hypercat:rels:isContentType","val
 RES=$(curl -sL  --cookie ./databox-jar -H "authorization:Token ${UI_AUTH_TOKEN}" --insecure "https://127.0.0.1/arbiter/cat")
 test_assert "$RES" "$EXPECTED" "Is the arbiter cat endpoint is ok?"
 
-#can we install the OS monitor driver
-PAYLOAD='{"manifest-version": 1,"name": "driver-os-monitor","version": "0.3.0","description": "A Databox driver to monitor the local os","author": "Anthony Brown <Anthony.Brown@nottingham.ac.uk> ()","license": "MIT","databox-type":"driver","tags": ["monitor","os"],"homepage": "https://github.com/me-box/driver-os-monitor","repository": {"type": "git","url": "git+https://github.com/me-box/driver-os-monitor.git"},"resource-requirements": {    "store":"core-store"}}'
-RES=$(curl -s  --insecure --cookie ./databox-jar -H "Content-Type: application/json" -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/install')
-EXPECTED='{"status":200,"msg":"Success"}'
-test_assert "$RES" "$EXPECTED" "Can we install the driver-os-monitor?"
 
-#can we install the OS monitor app
-PAYLOAD='{"manifest-version":1,"name":"app-os-monitor","databox-type":"app","version":"0.3.0","description":"An app in golang to plot the output of the os monitor driver.","author":"Tosh Brown <Anthony.Brown@nottingham.ac.uk>","license":"MIT","tags":["template","app","nodejs"],"homepage":"https://github.com/me-box/app-os-monitor","repository":{"type":"git","url":"git https://github.com/me-box/app-os-monitor"},"packages":[{"name":"OS monitor Plotter","purpose":"To visualize your databox load and free memory","install":"required","risks":"None.","benefits":"You can see the data!","datastores":["loadavg1","loadavg5","loadavg15","freemem","loadavg1Structured","freememStructured"],"enabled":true}],"allowed-combinations":[],"datasources":[{"type":"loadavg1","required":true,"name":"loadavg1","clientid":"loadavg1","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average 1 minute"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg1"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg1"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/loadavg1"}},{"type":"loadavg5","required":true,"name":"loadavg5","clientid":"loadavg5","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average over 5 minutes"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg5"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg5"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/loadavg5"}},{"type":"loadavg15","required":true,"name":"loadavg15","clientid":"loadavg15","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average over 15 minutes"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg15"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg15"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/loadavg15"}},{"type":"freemem","required":true,"name":"freemem","clientid":"freemem","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox free memory in bytes"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"freemem"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"freemem"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"bytes"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/blob/freemem"}},{"type":"loadavg1Structured","required":true,"name":"loadavg1Structured","clientid":"loadavg1Structured","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox load average 1 minute structured"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"loadavg1Structured"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"loadavg1Structured"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"%"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/loadavg1Structured"}},{"type":"freememStructured","required":true,"name":"freememStructured","clientid":"freememStructured","granularities":[],"hypercat":{"item-metadata":[{"rel":"urn:X-hypercat:rels:hasDescription:en","val":"Databox free memory in bytes structured"},{"rel":"urn:X-hypercat:rels:isContentType","val":"application/json"},{"rel":"urn:X-databox:rels:hasVendor","val":"Databox Inc."},{"rel":"urn:X-databox:rels:hasType","val":"freememStructured"},{"rel":"urn:X-databox:rels:hasDatasourceid","val":"freememStructured"},{"rel":"urn:X-databox:rels:hasStoreType","val":"ts"},{"rel":"urn:X-databox:rels:hasUnit","val":"bytes"}],"href":"tcp://driver-os-monitor-core-store:5555/ts/freememStructured"}}],"export-whitelist":[{"url":"https://export.amar.io/","description":"Exports the data to amar.io"}],"resource-requirements":{},"displayName":"os monitor","storeUrl":"http://localhost:8181/app/get/?name=app-os-monitor"}'
-RES=$(curl -s  --insecure --cookie ./databox-jar -H 'Content-Type: application/json' -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/install')
-EXPECTED='{"status":200,"msg":"Success"}'
-test_assert "$RES" "$EXPECTED" "Can we install the app-os-monitor?"
+#first install of the app and driver
+install_osmon_app_and_driver
 
-#is the OS monitor app up
+#first test of the app
+sleep 30 # long sleep to wait for images to be pulled if needed!
+test_app_os_monitor
+
+#Can we restart driver-os-monitor
+PAYLOAD='{"id":"driver-os-monitor"}'
+RES=$(curl -s  --insecure --cookie ./databox-jar -H 'Content-Type: application/json' -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/restart')
+EXPECTED='{"status":200,"msg":"Success"}'
+test_assert "$RES" "$EXPECTED" "Can we restart driver-os-monitor?"
+
+sleep 10
+
+#Can we restart app-os-monitor
+PAYLOAD='{"id":"app-os-monitor"}'
+RES=$(curl -s  --insecure --cookie ./databox-jar -H 'Content-Type: application/json' -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/restart')
+EXPECTED='{"status":200,"msg":"Success"}'
+test_assert "$RES" "$EXPECTED" "Can we restart app-os-monitor?"
+
+#second test of the app
+sleep 10
+test_app_os_monitor
+
+
+#Can we uninstall  driver-os-monitor
+PAYLOAD='{"id":"driver-os-monitor"}'
+RES=$(curl -s  --insecure --cookie ./databox-jar -H 'Content-Type: application/json' -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/uninstall')
+EXPECTED='{"status":"success"}'
+test_assert "$RES" "$EXPECTED" "Can we uninstall driver-os-monitor?"
+
+sleep 10
+
+#Can we uninstall app-os-monitor
+PAYLOAD='{"id":"app-os-monitor"}'
+RES=$(curl -s  --insecure --cookie ./databox-jar -H 'Content-Type: application/json' -H "authorization:Token ${UI_AUTH_TOKEN}" -X POST -d "${PAYLOAD}" -L 'https://127.0.0.1/api/uninstall')
+EXPECTED='{"status":"success"}'
+test_assert "$RES" "$EXPECTED" "Can we uninstall app-os-monitor?"
+
+sleep 10
+
+#can we reinstall os-monitor the app and driver
+install_osmon_app_and_driver
+
+#second test of the app
 sleep 30
-STATUS=$(curl -sL --cookie ./databox-jar -H "authorization:Token ${UI_AUTH_TOKEN}" --insecure -w "%{http_code}\\n" "https://127.0.0.1/app-os-monitor/ui" -o /dev/null)
-test_assert "$STATUS" 200 "Is the app-os-monitor/ui available?"
+test_app_os_monitor
+
+echo "Stopping data box"
+./databox-stop
+
+echo "Restarting data box"
+source ${DATABOX_CMD}
+
+#third test of the app
+sleep 30
+test_app_os_monitor
+
 
 exit 0
