Add a test for Docker DNS resolution

diff --git a/databox-test b/databox-test
--- a/databox-test
+++ b/databox-test
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+function red {
+  echo "\033[0;31m${1}\033[0m"
+}
+
 function fail {
     echo -e "[$( red FAILED )] ${1} \nERROR: ${2}"
     #output debug information
@@ -36,8 +40,17 @@ num=$2
 awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
 }
 
+# make sure we don't load anything from here
+rm ./slaStore/sladatastore.db >/dev/null 2>&1
 
-rm ./slaStore/sladatastore.db
+
+#test docker dns configuration
+docker run busybox nslookup google.com >/dev/null 2>&1
+if [[ "$?" == "1" ]]
+then
+  echo -e "[$( red FAILED )] TEST DNS \nERROR: Your docker DNS resolution seems to be broken. Help can be found here https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/"
+  exit 1
+fi
 
 #Start databox
 export DATABOX_TESTING=1
@@ -63,6 +76,8 @@ case "$1" in
     echo $'release - Tests databox release using images from databoxsystems on docker hub (built from tagged branches on Github) \n\n'
     exit 1
 esac
+
+
 
 
 UI_AUTH_TOKEN=$(cat ./certs/container-mananager-auth.json | jsonValue "token" 1)
